# =============================================
# BASE DE DATOS
# =============================================
spring.datasource.url=jdbc:mysql://127.0.0.1:3308/DYACESOFT?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# =============================================
# CORREO
# =============================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dyacesoft.2999154@gmail.com
spring.mail.password=fuotoicgvodrxggs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =============================================
# SESION
# =============================================
server.servlet.session.timeout=30m

# =============================================
# THYMELEAF
# =============================================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
